-- +goose Down
DROP TABLE IF EXISTS push_strategies CASCADE;
DROP TABLE IF EXISTS faq CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS templates CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS ad_events CASCADE;
DROP TABLE IF EXISTS stream_events CASCADE;
DROP TABLE IF EXISTS ad_config CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS enterprises CASCADE;
DROP TABLE IF EXISTS users CASCADE;
